### PR TITLE
[Issue-23] Only bridge NCT-eligible credits

### PR DESCRIPTION
**Pull request by pheuberger**
addresses issue #23.

We want to limit the type of credits being bridged to Regen to only NCT eligible tokens. The bridge function needs to check for the necessary attributes and revert if NCT criteria aren't met.

@dave can you please check that your E2E tests still work?

### CODE REVIEW

**Review by kargakis — APPROVED** [review]
Good work!

**Comment by dave** [comment]
This needs a couple of updates to `deploy-local.js`:

```
const [registry, tco2Factory, data] = await prepareToucanEnv(owner, owner);
```

should be:

```
const {registry, tco2Factory, nctPool, data} = await prepareToucanEnv(owner, owner);
```

... and:

```
const bridge = await deployBridge(regenBridgeAccount, registry.address);
```
should be:
```
const bridge = await deployBridge(regenBridgeAccount, registry.address, nctPool.address);
```

... however this seems to be failing for all bridge requests... Does the nct pool contract need to be configured somehow? I think we need to have it configured like it is in production...

**Comment by dave** [comment]
OK it looks like this is working with those fixes, but I'm getting a `Methodology not accepted` error... it looks like by default the nctPool contract deny all projects until it's configured... How do we configure it like it is in production?

**Comment by pheuberger** [comment]
awesome, thank you for the feedback, @dave! can i extend your genesis file to also include a flag per project that says that the project methodology should be added to the eligible methodologies on the pool? because i need a way to also disable a methodology to make the test pass

**Review by kargakis — APPROVED** [review]

**Pull request merged**
