### PR TITLE
Config refactor

### PR DESCRIPTION
**Pull request by dave**
@pheuberger @kargakis

### CODE REVIEW

**Comment by dave** [comment]
Re: https://github.com/rnd-inc/toucan-bridge-service/pull/177

**Review by pheuberger — APPROVED** [review]
👍

**Comment by dave** [comment]
> just wondering, why `ETH_*` and not `POLYGON_*` or `EVM_`?

Just matching the naming in https://github.com/rnd-inc/toucan-bridge-service/blob/main/config/config.go ... I think "ETH" was chosen just to differentiate from "REGEN"... re: https://github.com/rnd-inc/toucan-bridge-service/pull/163

**Comment by pheuberger** [comment]
> > just wondering, why `ETH_*` and not `POLYGON_*` or `EVM_`?
> 
> Just matching the naming in https://github.com/rnd-inc/toucan-bridge-service/blob/main/config/config.go ... I think "ETH" was chosen just to differentiate from "REGEN"... re: [rnd-inc/toucan-bridge-service#163](https://github.com/rnd-inc/toucan-bridge-service/pull

gotcha! it’s a little bit wrong but if it’s just there to differentiate between regen and everything else, why not. can be changed if regen ever wants to reuse/extend the micro service if they want to bridge to ethereum

**Pull request merged**
